In [ ]:
#! pip install numpy pandas matplotlib sklearn
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, auc
y_train = pd.read_csv("Y_train.csv")
y_valid = pd.read_csv("Y_valid.csv")
y_train.info()
X_train = pd.read_csv("X_train_all_range.csv") # index_col = [0]
X_valid = pd.read_csv("X_valid_all_range.csv")


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16760 entries, 0 to 16759
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mort_icu  16760 non-null  int64
dtypes: int64(1)
memory usage: 131.1 KB


In [ ]:
max_depth=1
n_estimators=260
learning_rate=0.25

# **n_estimator**

In [ ]:
param_test1 = {'n_estimators':[50, 75, 100, 125, 150, 200, 260]}
abc1 = GridSearchCV(estimator = AdaBoostClassifier (base_estimator=DecisionTreeClassifier(max_depth=1, random_state=1), learning_rate=0.25, random_state=1), param_grid = param_test1, scoring='roc_auc', cv=5)
abc1.fit(X_train,y_train)
abc1.best_params_, abc1.best_score_

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

({'n_estimators': 125}, 0.8786222026628483)

In [ ]:
abc1.cv_results_

{'mean_fit_time': array([ 6.9747541 , 10.31576376, 13.94373617, 17.10739613, 20.36012578,
        27.25809875, 35.60128746]),
 'std_fit_time': array([0.31047963, 0.21695657, 0.66144042, 0.20286308, 0.05638512,
        0.24873486, 0.37345572]),
 'mean_score_time': array([0.1323009 , 0.18650041, 0.28970628, 0.34171338, 0.36639419,
        0.49298606, 0.62230964]),
 'std_score_time': array([0.00380249, 0.00274299, 0.08088535, 0.05396019, 0.00876336,
        0.0114609 , 0.01158908]),
 'param_n_estimators': masked_array(data=[50, 75, 100, 125, 150, 200, 260],
              mask=[False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_estimators': 50},
  {'n_estimators': 75},
  {'n_estimators': 100},
  {'n_estimators': 125},
  {'n_estimators': 150},
  {'n_estimators': 200},
  {'n_estimators': 260}],
 'split0_test_score': array([0.87703277, 0.88397759, 0.8864644 , 0.88888553, 0.88317755,
        0.88502591, 0.87660516]),
 'split1_t

under learning rate = 0.25, max_depth = 1
-> n_estimator best range: 100 ~ 200 and best result 125 

In [ ]:
param_test1 = {'n_estimators':[110, 120, 125, 130, 140, 160, 170, 180, 190]}
abc1 = GridSearchCV(estimator = AdaBoostClassifier (base_estimator=DecisionTreeClassifier(max_depth=1, random_state=1), learning_rate=0.25, random_state=1), param_grid = param_test1, scoring='roc_auc', cv=5)
abc1.fit(X_train,y_train)
print ("##################Best result", abc1.best_params_, abc1.best_score_)
print (abc1.cv_results_)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

##################Best result {'n_estimators': 130} 0.878926978580296
{'mean_fit_time': array([15.4484479 , 16.39735055, 16.95259795, 17.80302434, 19.10517745,
       21.85893407, 23.03350315, 24.58190846, 25.89960866]), 'std_fit_time': array([0.47628808, 0.26596118, 0.05217068, 0.26597176, 0.27206   ,
       0.3374563 , 0.08057069, 0.24952812, 0.27542886]), 'mean_score_time': array([0.26939921, 0.28904061, 0.29868236, 0.31234517, 0.33312964,
       0.38885374, 0.41630082, 0.43485694, 0.45520911]), 'std_score_time': array([0.00765286, 0.00553999, 0.00539962, 0.00496626, 0.00390082,
       0.00881612, 0.01685641, 0.00827048, 0.0069982 ]), 'param_n_estimators': masked_array(data=[110, 120, 125, 130, 140, 160, 170, 180, 190],
             mask=[False, False, False, False, False, False, False, False,
                   False],
       fill_value='?',
            dtype=object), 'params': [{'n_estimators': 110}, {'n_estimators': 120}, {'n_estimators': 125}, {'n_estimators': 130}, {'n_estimato

under learning rate = 0.25, max_depth = 1
-> n_estimator best range: 110 ~ 140 and best result 130 

# **Max_depth**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
param_test2 = {'base_estimator__max_depth':range(1,17,4),
              'n_estimators':[130],
              'learning_rate':[0.25]}
abc2 = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())
abc2 = GridSearchCV(abc2, param_test2,scoring='roc_auc',cv=5)
abc2.fit(X_train,y_train)
print ("##################Best result", abc2.best_params_, abc2.best_score_)
print (abc2.cv_results_)

##################Best result {'base_estimator__max_depth': 1, 'learning_rate': 0.25, 'n_estimators': 130} 0.878926978580296
{'mean_fit_time': array([ 17.81969299,  79.63963275, 141.45721307, 193.94740872]), 'std_fit_time': array([0.21285298, 0.69090338, 0.49763457, 0.64342153]), 'mean_score_time': array([0.34441652, 0.3353909 , 0.34548945, 0.3536706 ]), 'std_score_time': array([0.0578092 , 0.00591046, 0.00450385, 0.01345473]), 'param_base_estimator__max_depth': masked_array(data=[1, 5, 9, 13],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'param_learning_rate': masked_array(data=[0.25, 0.25, 0.25, 0.25],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'param_n_estimators': masked_array(data=[130, 130, 130, 130],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'base_estimator__max_depth': 1, 'learning_rate': 0.25, 'n_estimat

# **Learning rate & n_estimator**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
param_test3 = {'n_estimators':range(110, 140, 5),'learning_rate':[0.01,0.25, 0.03,0.05,0.75,0.1]}
abc3 = GridSearchCV(estimator = AdaBoostClassifier (base_estimator=DecisionTreeClassifier(max_depth=1, random_state=1), random_state=1), param_grid = param_test3, scoring='roc_auc', cv=5)
abc3.fit(X_train,y_train)
print ("##################Best result", abc2.best_params_, abc2.best_score_)
print (abc2.cv_results_)

# **Backup**

In [ ]:
abc = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())

parameters = {'base_estimator__max_depth':[i for i in range(1,16,1)],
              'base_estimator__min_samples_leaf':range(10,100,20),
              'n_estimators':[10,50,250,500, 1000],
              'learning_rate':[0.01,0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]}

abc0 = GridSearchCV(abc, parameters,scoring='roc_auc',cv=5)
abc0.fit(X_train,y_train)
abc0.best_params_, abc0.best_score_

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
param_test2 = {'max_depth':range(0,17,4)}
abc2 = GridSearchCV(estimator = AdaBoostClassifier (base_estimator=DecisionTreeClassifier(max_depth=1, random_state=1), learning_rate=0.25, random_state=1), param_grid = param_test1, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
abc2.fit(X_train,y_train)
abc2.best_params_, abc2.best_score_

In [ ]:
param_test3 = {'min_samples_split':range(100,1600,200),'min_samples_leaf':range(10,100,20)}
gsearch3 = GridSearchCV(estimator = GradientBoostingClassifier(max_depth=12,n_estimators=80,learning_rate=0.1,max_features='sqrt',subsample=0.8,random_state=10),
param_grid = param_test3, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
gsearch3.fit(X_train,y_train)
gsearch3.best_params_, gsearch3.best_score_

In [ ]:
param_test4 = {'subsample':[0.8,1]}
gsearch4 = GridSearchCV(estimator = GradientBoostingClassifier(min_samples_leaf=70,min_samples_split=1100,max_depth=12,n_estimators=80,learning_rate=0.1,max_features='sqrt',random_state=10),
param_grid = param_test4, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
gsearch4.fit(X_train,y_train)
gsearch4.best_params_, gsearch4.best_score_

In [ ]:
param_test5 = {'n_estimators':[160,200,230,240,260,280,300],'learning_rate':[0.01,0.03,0.05,0.04,0.1]}
gsearch5 = GridSearchCV(estimator = GradientBoostingClassifier(min_samples_leaf=70,min_samples_split=1100,max_depth=12,n_estimators=80,learning_rate=0.1,max_features='sqrt',random_state=10),
param_grid = param_test5, scoring='roc_auc',n_jobs=4,iid=False, cv=5)
gsearch5.fit(X_train,y_train)
gsearch5.best_params_, gsearch5.best_score_

In [ ]:
gbc=GradientBoostingClassifier(n_estimators=240,learning_rate=0.05,min_samples_leaf=70,min_samples_split=1100,max_depth=12,max_features='sqrt',random_state=10)
gbc.fit(X_train,y_train)
y_valid_scores = gbc.predict_proba(X_valid)[:, 1]
fpr, tpr, threshold = roc_curve(y_valid, y_valid_scores)
auc_valid = auc(fpr, tpr)
plt.figure(figsize=(10,8))
plt.plot([0,1],[0,1],'k--')
plt.plot(fpr, tpr, "r", linewidth=3)
plt.grid()
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("AdaBoostClassifier ROC Curve")
plt.xlim(0,1)
plt.ylim(0,1)
plt.text(0.15, 0.9, "AUC = " + str (round (auc_valid, 4)))
plt.show